[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "League of Legends Pick/Ban Overlay with manual input"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.0",
    "gunicorn>=23.0.0"
]